"""Transparent project initialization from a directory of VTK meshes."""

from __future__ import annotations

import io
import os
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from diffeoforge.atomic_io import write_text_safely
from diffeoforge.config import (
    ConfigurationError,
    validate_input_paths,
    validate_schema,
)
from diffeoforge.diagnostics import DEFAULT_CONTAINER_IMAGE
from diffeoforge.mesh import inspect_inputs
from diffeoforge.report import PreflightResult, make_preflight_result

SUPPORTED_UNITS = ("unitless", "micrometer", "millimeter", "centimeter", "meter")
EXPLORATORY_RATIOS = {
    "attachment_kernel_width": 0.10,
    "deformation_kernel_width": 0.15,
    "initial_control_point_spacing": 0.15,
    "noise_std": 0.025,
}
_CONFIG_MARKER = "# Generated by diffeoforge init."


@dataclass(frozen=True)
class InitializationResult:
    """Created configuration and the preflight evidence used to create it."""

    config_path: Path
    config: Mapping[str, Any]
    preflight: PreflightResult
    derived_parameters: tuple[str, ...]


def detect_template(mesh_directory: Path | str) -> Path | None:
    """Detect only an unambiguous file literally named ``template.vtk``."""

    directory = Path(mesh_directory).expanduser().resolve()
    if not directory.is_dir():
        raise ConfigurationError(f"Mesh directory does not exist: {directory}")
    matches = sorted(
        path.resolve()
        for path in directory.iterdir()
        if path.is_file() and path.name.casefold() == "template.vtk"
    )
    if len(matches) > 1:
        raise ConfigurationError(
            "More than one case-insensitive template.vtk candidate exists; pass --template."
        )
    return matches[0] if matches else None


def _resolve_template(mesh_directory: Path, template: Path | str | None) -> Path:
    if template is None:
        detected = detect_template(mesh_directory)
        if detected is None:
            raise ConfigurationError(
                "No file named template.vtk was found. Pass --template with the initial "
                "template mesh; DiffeoForge will not guess one from the subjects."
            )
        return detected

    candidate = Path(template).expanduser()
    if not candidate.is_absolute():
        candidate = mesh_directory / candidate
    candidate = candidate.resolve()
    if not candidate.is_file():
        raise ConfigurationError(f"Template mesh does not exist: {candidate}")
    return candidate


def _portable_path(path: Path, base_directory: Path) -> str:
    try:
        relative = os.path.relpath(path, start=base_directory)
    except ValueError:
        return path.as_posix()
    value = Path(relative).as_posix()
    return f"./{value}" if not value.startswith((".", "/")) else value


def _scaled_value(diagonal: float, ratio: float) -> float:
    return float(f"{diagonal * ratio:.8g}")


def _parameter_value(
    name: str,
    override: float | None,
    diagonal: float,
    derived: list[str],
) -> float:
    if override is not None:
        return override
    derived.append(name)
    return _scaled_value(diagonal, EXPLORATORY_RATIOS[name])


def _header(config: Mapping[str, Any], derived_parameters: tuple[str, ...]) -> str:
    lines = [
        _CONFIG_MARKER,
        "# Review every value before scientific use; schema validity is not biological validation.",
    ]
    if derived_parameters:
        lines.extend(
            (
                "# The following exploratory starting values were scaled from the template",
                "# bounding-box diagonal and are not scientifically validated defaults:",
            )
        )
        model = config["model"]
        values = {
            "attachment_kernel_width": model["attachment"]["kernel_width"],
            "deformation_kernel_width": model["deformation"]["kernel_width"],
            "initial_control_point_spacing": model["deformation"]["initial_control_point_spacing"],
            "noise_std": model["noise_std"],
        }
        for name in derived_parameters:
            lines.append(
                f"#   {name}: {values[name]} ({EXPLORATORY_RATIOS[name]:.3g} x template diagonal)"
            )
    return "\n".join(lines) + "\n"


def initialize_project(
    mesh_directory: Path | str,
    *,
    units: str,
    config_path: Path | str = "atlas.yaml",
    template: Path | str | None = None,
    subject_pattern: str = "*.vtk",
    project_name: str | None = None,
    runs_directory: Path | str | None = None,
    attachment_kernel_width: float | None = None,
    deformation_kernel_width: float | None = None,
    initial_control_point_spacing: float | None = None,
    noise_std: float | None = None,
    threads: int | None = None,
    random_seed: int = 20260715,
    image: str = DEFAULT_CONTAINER_IMAGE,
    overwrite: bool = False,
) -> InitializationResult:
    """Validate meshes and write one explicit, runnable starter configuration."""

    directory = Path(mesh_directory).expanduser().resolve()
    if not directory.is_dir():
        raise ConfigurationError(f"Mesh directory does not exist: {directory}")

    destination_candidate = Path(config_path).expanduser()
    if destination_candidate.is_symlink():
        raise ConfigurationError(
            "Refusing to initialize through a symbolic-link configuration path: "
            f"{destination_candidate.absolute()}"
        )
    destination = destination_candidate.resolve()
    if destination.exists() and not overwrite:
        raise ConfigurationError(
            f"Configuration already exists and will not be overwritten: {destination}"
        )
    if destination.exists() and overwrite:
        if not destination.is_file():
            raise ConfigurationError(
                "Refusing --force because the existing configuration path is not a regular "
                f"file: {destination}"
            )
        try:
            with destination.open(encoding="utf-8") as handle:
                first_line = handle.readline().rstrip("\r\n")
        except OSError as error:
            raise ConfigurationError(
                f"Could not verify existing configuration {destination}: {error}"
            ) from error
        if first_line != _CONFIG_MARKER:
            raise ConfigurationError(
                "Refusing --force because the existing configuration is not recognized as "
                f"generated by DiffeoForge: {destination}"
            )
    template_path = _resolve_template(directory, template)
    config_base = destination.parent

    if runs_directory is None:
        run_path_value = "./runs"
    else:
        run_path = Path(runs_directory).expanduser()
        run_path_value = (
            _portable_path(run_path.resolve(), config_base)
            if run_path.is_absolute()
            else run_path.as_posix()
        )

    default_name_source = (
        directory.parent.name
        if directory.name.casefold() in {"mesh", "meshes", "data"}
        else directory.name
    )
    provisional: dict[str, Any] = {
        "schema_version": "0.1",
        "project": {"name": project_name or f"{default_name_source}-atlas"},
        "input": {
            "directory": _portable_path(directory, config_base),
            "subject_pattern": subject_pattern,
            "template": _portable_path(template_path, config_base),
            "units": units,
        },
        "model": {
            "type": "deterministic_atlas",
            "dimension": 3,
            "object_id": "surface",
            "attachment": {"type": "current", "kernel_width": 1.0},
            "deformation": {
                "kernel_width": 1.0,
                "timepoints": 10,
                "initial_control_point_spacing": 1.0,
                "use_rk2": False,
            },
            "noise_std": 1.0,
        },
        "optimization": {
            "method": "gradient_ascent",
            "max_iterations": 100,
            "initial_step_size": 0.01,
            "convergence_tolerance": 0.0001,
            "downsampling_factor": 1,
            "max_line_search_iterations": 10,
            "save_every_n_iterations": 100,
            "print_every_n_iterations": 1,
            "scale_initial_step_size": True,
            "use_sobolev_gradient": True,
            "sobolev_kernel_width_ratio": 1.0,
            "freeze_template": False,
            "freeze_control_points": False,
        },
        "runtime": {
            "backend": "deformetrica_reference",
            "device": "cpu",
            "threads": (threads if threads is not None else max(1, min(4, os.cpu_count() or 1))),
            "processes": 1,
            "precision": "float32",
            "random_seed": random_seed,
            "kernel_backend": "keops",
            "verbosity": "INFO",
            "launcher": {"type": "container", "engine": "docker", "image": image},
        },
        "output": {"directory": run_path_value, "retain_flow_meshes": True},
    }
    validate_schema(provisional)
    inputs = validate_input_paths(provisional, destination)
    template_metadata, subjects = inspect_inputs(inputs)

    derived: list[str] = []
    diagonal = template_metadata.bounding_box_diagonal
    provisional["model"]["attachment"]["kernel_width"] = _parameter_value(
        "attachment_kernel_width", attachment_kernel_width, diagonal, derived
    )
    provisional["model"]["deformation"]["kernel_width"] = _parameter_value(
        "deformation_kernel_width", deformation_kernel_width, diagonal, derived
    )
    provisional["model"]["deformation"]["initial_control_point_spacing"] = _parameter_value(
        "initial_control_point_spacing",
        initial_control_point_spacing,
        diagonal,
        derived,
    )
    provisional["model"]["noise_std"] = _parameter_value("noise_std", noise_std, diagonal, derived)
    validate_schema(provisional)

    derived_parameters = tuple(derived)
    rendered = io.StringIO(newline="\n")
    rendered.write(_header(provisional, derived_parameters))
    yaml.safe_dump(
        provisional,
        rendered,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
    )
    try:
        write_text_safely(destination, rendered.getvalue(), overwrite=overwrite)
    except FileExistsError as error:
        raise ConfigurationError(
            f"Configuration already exists and will not be overwritten: {destination}"
        ) from error
    except OSError as error:
        raise ConfigurationError(f"Could not write configuration {destination}: {error}") from error

    preflight = make_preflight_result(
        destination,
        provisional,
        inputs,
        template_metadata,
        subjects,
    )
    return InitializationResult(
        config_path=destination,
        config=provisional,
        preflight=preflight,
        derived_parameters=derived_parameters,
    )
