"""Auditable pre-compute workload planning for the dense modern engine."""

from __future__ import annotations

import html
import json
import os
import platform
import shutil
import uuid
from importlib.resources import files
from pathlib import Path
from typing import Any

import jsonschema

from diffeoforge import __version__
from diffeoforge.config import InputSummary, validate_input_paths
from diffeoforge.diagnostics import _physical_memory_bytes
from diffeoforge.mesh import MeshMetadata, inspect_inputs, sha256_file
from diffeoforge.modern_workflow import (
    load_modern_workflow_config,
    validate_modern_analysis_dimensions,
)

WORKLOAD_VERSION = "0.1"
REPORT_JSON_NAME = "workload.json"
REPORT_HTML_NAME = "workload.html"
HTML_MARKER = "<!-- Generated by DiffeoForge modern-plan; safe to replace with --force. -->"
SCIENTIFIC_BOUNDARY = (
    "Operation counts and known tensor payloads for the current dense CPU/float64 "
    "implementation only. This is not a peak-RAM predictor, runtime forecast, benchmark, "
    "guarantee of 300-specimen feasibility, GPU estimate, or Deformetrica resource model. "
    "Autograd intermediates, allocator behavior, BLAS threading, operating-system load, "
    "and future implementations can materially change actual resource use."
)


class ModernWorkloadError(RuntimeError):
    """Raised when a modern workload report cannot be collected or published safely."""


def _schema() -> dict[str, Any]:
    resource = files("diffeoforge.schema").joinpath("modern-workload-v0.1.json")
    return json.loads(resource.read_text(encoding="utf-8"))


def _validate_report(report: dict[str, Any]) -> None:
    try:
        jsonschema.Draft202012Validator(_schema()).validate(report)
    except jsonschema.ValidationError as error:
        location = ".".join(str(part) for part in error.absolute_path) or "document"
        raise ModernWorkloadError(
            f"Modern workload schema validation failed at {location}: {error.message}"
        ) from error


def _mesh_record(label: str, role: str, metadata: MeshMetadata) -> dict[str, Any]:
    return {
        "label": label,
        "role": role,
        "bytes": metadata.bytes,
        "sha256": metadata.sha256,
        "points": metadata.points,
        "triangles": metadata.cells,
    }


def _existing_parent(path: Path) -> Path:
    candidate = path.resolve()
    while not candidate.exists() and candidate != candidate.parent:
        candidate = candidate.parent
    if not candidate.is_dir():
        raise ModernWorkloadError(f"No existing parent directory for disk inspection: {path}")
    return candidate


def _host_observations(output_directory: Path) -> dict[str, Any]:
    memory = _physical_memory_bytes()
    try:
        free_disk = shutil.disk_usage(_existing_parent(output_directory)).free
    except OSError:
        free_disk = None
    return {
        "platform": platform.platform(),
        "logical_cpus": os.cpu_count(),
        "physical_memory_bytes": memory,
        "output_filesystem_free_bytes": free_disk,
    }


def _largest_dense_pair(
    template: dict[str, Any],
    subjects: list[dict[str, Any]],
    control_points: int,
) -> dict[str, Any]:
    candidates = [
        ("deformation_control_control", None, control_points, control_points),
        ("template_flow", None, template["points"], control_points),
        ("template_attachment_self", None, template["triangles"], template["triangles"]),
    ]
    for subject in subjects:
        candidates.extend(
            [
                (
                    "subject_attachment_self",
                    subject["label"],
                    subject["triangles"],
                    subject["triangles"],
                ),
                (
                    "template_subject_attachment_cross",
                    subject["label"],
                    template["triangles"],
                    subject["triangles"],
                ),
            ]
        )
    operation, label, rows, columns = max(
        candidates,
        key=lambda value: value[2] * value[3],
    )
    elements = rows * columns
    return {
        "operation": operation,
        "subject_label": label,
        "rows": rows,
        "columns": columns,
        "pair_elements": elements,
        "float64_matrix_bytes": elements * 8,
        "float64_xyz_difference_tensor_bytes": elements * 3 * 8,
    }


def _operation_model(
    config: dict[str, Any],
    template: dict[str, Any],
    subjects: list[dict[str, Any]],
) -> dict[str, Any]:
    subject_count = len(subjects)
    control_points = config["initialization"]["control_points"]["count"]
    deformation = config["model"]["deformation"]
    time_steps = deformation["timepoints"] - 1
    shooting_calls_per_step = 2 if deformation["shooting_integrator"] == "euler" else 6
    flow_calls_per_step = 1 if deformation["flow_integrator"] == "euler" else 2
    extrapolation_calls = 4 if deformation["flow_integrator"] == "deformetrica_heun" else 0
    attachment_pairs = sum(
        template["triangles"] ** 2
        + subject["triangles"] ** 2
        + template["triangles"] * subject["triangles"]
        for subject in subjects
    )
    attachment_calls = 3 * subject_count
    shooting_calls = subject_count * time_steps * shooting_calls_per_step
    shooting_pairs = shooting_calls * control_points**2
    flow_calls = subject_count * time_steps * flow_calls_per_step
    flow_pairs = flow_calls * template["points"] * control_points
    extrapolation_total_calls = subject_count * extrapolation_calls
    extrapolation_pairs = extrapolation_total_calls * control_points**2
    energy_calls = subject_count
    energy_pairs = energy_calls * control_points**2
    gaussian_calls = (
        attachment_calls
        + shooting_calls
        + flow_calls
        + extrapolation_total_calls
        + energy_calls
    )
    gaussian_pairs = (
        attachment_pairs
        + shooting_pairs
        + flow_pairs
        + extrapolation_pairs
        + energy_pairs
    )
    return {
        "definitions": {
            "pair_element": "one entry of a dense Gaussian kernel matrix",
            "attachment_per_subject": (
                "template_faces^2 + subject_faces^2 + template_faces * subject_faces"
            ),
            "shooting_per_step": "2 * control_points^2 for Euler; 6 * control_points^2 for RK2",
            "flow_per_step": (
                "template_points * control_points for Euler; twice that for Heun variants"
            ),
            "deformetrica_heun_extrapolation": "4 * control_points^2 once per subject objective",
            "deformation_energy": "control_points^2 once per subject objective",
        },
        "one_objective_forward": {
            "dense_gaussian_calls": gaussian_calls,
            "dense_gaussian_pair_elements": gaussian_pairs,
            "attachment": {
                "calls": attachment_calls,
                "pair_elements": attachment_pairs,
                "orientation_pair_elements": (
                    attachment_pairs if config["model"]["attachment"]["type"] == "varifold" else 0
                ),
            },
            "shooting": {"calls": shooting_calls, "pair_elements": shooting_pairs},
            "template_flow": {"calls": flow_calls, "pair_elements": flow_pairs},
            "deformetrica_heun_extrapolation": {
                "calls": extrapolation_total_calls,
                "pair_elements": extrapolation_pairs,
            },
            "deformation_energy": {"calls": energy_calls, "pair_elements": energy_pairs},
        },
        "largest_dense_pair": _largest_dense_pair(template, subjects, control_points),
    }


def _payload_model(
    config: dict[str, Any],
    template: dict[str, Any],
    subjects: list[dict[str, Any]],
    largest_dense_pair: dict[str, Any],
) -> dict[str, int]:
    subject_count = len(subjects)
    control_points = config["initialization"]["control_points"]["count"]
    timepoints = config["model"]["deformation"]["timepoints"]
    mesh_tensors = (
        (template["points"] * 3 + template["triangles"] * 3)
        + sum(subject["points"] * 3 + subject["triangles"] * 3 for subject in subjects)
    ) * 8
    control_tensor = control_points * 3 * 8
    momenta_tensor = subject_count * control_points * 3 * 8
    persistent = mesh_tensors + control_tensor + momenta_tensor
    retained_paths = subject_count * timepoints * (
        2 * control_points * 3 + template["points"] * 3
    ) * 8
    largest_difference = largest_dense_pair["float64_xyz_difference_tensor_bytes"]
    return {
        "engine_initial_mesh_tensor_bytes": mesh_tensors,
        "engine_initial_control_point_tensor_bytes": control_tensor,
        "engine_initial_momenta_tensor_bytes": momenta_tensor,
        "engine_initial_persistent_tensor_bytes": persistent,
        "objective_retained_trajectory_and_template_path_bytes": retained_paths,
        "largest_single_dense_xyz_difference_tensor_bytes": largest_difference,
        "known_payload_arithmetic_subtotal_bytes": persistent
        + retained_paths
        + largest_difference,
    }


def _pca_output_bound(config: dict[str, Any], subjects: int, control_points: int) -> dict[str, int]:
    available = min(subjects - 1, 3 * control_points)
    retained_setting = config["analysis"]["pca_components"]
    retained = available if retained_setting is None else min(available, retained_setting)
    deformation_setting = config["analysis"]["deformation_components"]
    deformations = retained if deformation_setting is None else min(retained, deformation_setting)
    return {
        "maximum_retained_components": retained,
        "maximum_deformation_components": deformations,
        "maximum_pca_meshes_including_mean": 1 + 2 * deformations,
        "maximum_bundle_vtk_meshes": 1 + subjects + 1 + 2 * deformations,
    }


def collect_modern_workload(
    config_path: Path | str,
    *,
    host_observations: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Collect exact input dimensions and transparent dense-operation formulas."""

    source = Path(config_path).expanduser().resolve()
    config = load_modern_workflow_config(source)
    inputs: InputSummary = validate_input_paths(config, source)
    validate_modern_analysis_dimensions(config, len(inputs.subjects))
    template_metadata, subject_metadata = inspect_inputs(inputs)
    template = _mesh_record(inputs.template.name, "template", template_metadata)
    subjects = [
        _mesh_record(path.name, "subject", metadata)
        for path, metadata in zip(inputs.subjects, subject_metadata, strict=True)
    ]
    operation = _operation_model(config, template, subjects)
    payload = _payload_model(config, template, subjects, operation["largest_dense_pair"])
    optimizer = config["optimization"]
    evaluation_upper_bound = 1 + optimizer["max_cycles"] * len(optimizer["block_order"]) * (
        1 + optimizer["max_line_search_iterations"]
    )
    output = Path(config["output"]["directory"]).expanduser()
    if not output.is_absolute():
        output = source.parent / output
    host = _host_observations(output) if host_observations is None else dict(host_observations)
    memory = host.get("physical_memory_bytes")
    warnings = [
        "Actual peak RAM and runtime require measurement on the final implementation and cohort.",
        "The optimizer pair bound excludes final reconstruction/PCA endpoint generation, "
        "PCA SVD, mesh-quality verification, report generation, and file I/O.",
    ]
    if len(subjects) >= 300:
        warnings.append(
            "The cohort contains at least 300 subjects; production scaling is not validated."
        )
    if isinstance(memory, int) and memory > 0:
        if payload["largest_single_dense_xyz_difference_tensor_bytes"] > memory:
            warnings.append(
                "One known dense XYZ-difference tensor exceeds detected physical memory."
            )
        if payload["known_payload_arithmetic_subtotal_bytes"] > memory:
            warnings.append(
                "The known payload arithmetic subtotal exceeds detected physical memory."
            )
    report = {
        "workload_version": WORKLOAD_VERSION,
        "engine": {
            "id": "diffeoforge_modern_dense",
            "diffeoforge": __version__,
            "device": config["runtime"]["device"],
            "precision": config["runtime"]["precision"],
            "bytes_per_float": 8,
        },
        "source_config": {
            "filename": source.name,
            "sha256": sha256_file(source),
            "project": config["project"]["name"],
        },
        "input": {
            "template": template,
            "subjects": subjects,
            "subject_count": len(subjects),
            "source_file_bytes": template["bytes"]
            + sum(subject["bytes"] for subject in subjects),
        },
        "configuration": {
            "control_points": config["initialization"]["control_points"]["count"],
            "timepoints": config["model"]["deformation"]["timepoints"],
            "shooting_integrator": config["model"]["deformation"]["shooting_integrator"],
            "flow_integrator": config["model"]["deformation"]["flow_integrator"],
            "attachment_type": config["model"]["attachment"]["type"],
            "max_cycles": optimizer["max_cycles"],
            "block_order": list(optimizer["block_order"]),
            "max_line_search_iterations": optimizer["max_line_search_iterations"],
            "threads": config["runtime"]["threads"],
            "procrustes_enabled": config["preprocessing"]["procrustes"]["enabled"],
        },
        "operation_model": operation,
        "optimizer_bound": {
            "formula": "1 + max_cycles * parameter_blocks * (1 + max_line_search_iterations)",
            "parameter_blocks": len(optimizer["block_order"]),
            "objective_gradient_evaluation_upper_bound": evaluation_upper_bound,
            "dense_gaussian_pair_elements_upper_bound": evaluation_upper_bound
            * operation["one_objective_forward"]["dense_gaussian_pair_elements"],
        },
        "payload_model": payload,
        "output_bound": _pca_output_bound(
            config,
            len(subjects),
            config["initialization"]["control_points"]["count"],
        ),
        "host_observations": host,
        "warnings": warnings,
        "scientific_boundary": SCIENTIFIC_BOUNDARY,
    }
    _validate_report(report)
    return report


def _gib(value: int | None) -> str:
    return "unknown" if value is None else f"{value / 1024**3:.3f} GiB"


def render_modern_workload_html(report: dict[str, Any]) -> str:
    """Render a self-contained, escaped review report."""

    input_record = report["input"]
    operation = report["operation_model"]
    payload = report["payload_model"]
    host = report["host_observations"]
    subject_rows = "".join(
        "<tr>"
        f"<td>{html.escape(subject['label'])}</td>"
        f"<td>{subject['points']:,}</td>"
        f"<td>{subject['triangles']:,}</td>"
        f"<td>{subject['bytes']:,}</td>"
        "</tr>"
        for subject in input_record["subjects"]
    )
    warnings = "".join(f"<li>{html.escape(value)}</li>" for value in report["warnings"])
    boundary = html.escape(report["scientific_boundary"])
    source = report["source_config"]
    configuration = report["configuration"]
    optimizer_bound = report["optimizer_bound"]
    objective = operation["one_objective_forward"]
    largest = operation["largest_dense_pair"]
    project = html.escape(source["project"])
    config_filename = html.escape(source["filename"])
    attachment = html.escape(configuration["attachment_type"])
    shooting = html.escape(configuration["shooting_integrator"])
    flow = html.escape(configuration["flow_integrator"])
    reviewed_items = "".join(
        f"<li>{label}: {value}</li>"
        for label, value in (
            ("Subjects", f"{input_record['subject_count']:,}"),
            ("Control points", f"{configuration['control_points']:,}"),
            ("Time points", f"{configuration['timepoints']:,}"),
            ("Attachment", attachment),
            ("Integrators", f"{shooting} shooting / {flow} flow"),
            (
                "Optimizer evaluation upper bound",
                f"{optimizer_bound['objective_gradient_evaluation_upper_bound']:,}",
            ),
        )
    )
    operation_items = "".join(
        f"<li>{label}: {value}</li>"
        for label, value in (
            ("Gaussian calls per objective forward", f"{objective['dense_gaussian_calls']:,}"),
            (
                "Gaussian pair elements per objective forward",
                f"{objective['dense_gaussian_pair_elements']:,}",
            ),
            (
                "Pair-element upper bound over optimizer",
                f"{optimizer_bound['dense_gaussian_pair_elements_upper_bound']:,}",
            ),
            (
                "Largest pair",
                f"{html.escape(largest['operation'])}, {largest['rows']:,} × "
                f"{largest['columns']:,}",
            ),
        )
    )
    payload_items = "".join(
        f"<li>{label}: {_gib(value)}</li>"
        for label, value in (
            ("Initial engine tensors", payload["engine_initial_persistent_tensor_bytes"]),
            (
                "Retained trajectory/path payload",
                payload["objective_retained_trajectory_and_template_path_bytes"],
            ),
            (
                "Largest single XYZ-difference tensor",
                payload["largest_single_dense_xyz_difference_tensor_bytes"],
            ),
            ("Known arithmetic subtotal", payload["known_payload_arithmetic_subtotal_bytes"]),
            ("Detected physical memory", host.get("physical_memory_bytes")),
            (
                "Detected output-filesystem free space",
                host.get("output_filesystem_free_bytes"),
            ),
        )
    )
    template_record = input_record["template"]
    template_row = (
        f"<tr><td>{html.escape(template_record['label'])} (template)</td>"
        f"<td>{template_record['points']:,}</td>"
        f"<td>{template_record['triangles']:,}</td>"
        f"<td>{template_record['bytes']:,}</td></tr>"
    )
    return f"""{HTML_MARKER}
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>DiffeoForge modern workload plan</title>
<style>
body{{font:16px/1.5 system-ui,sans-serif;max-width:1100px;margin:2rem auto;
padding:0 1rem;color:#18212b}}
h1,h2{{color:#153b5b}} table{{border-collapse:collapse;width:100%}}
th,td{{border:1px solid #ccd6df;padding:.45rem;text-align:left}}
th{{background:#eef4f8}} code{{background:#eef4f8;padding:.1rem .3rem}}
.warning{{border-left:5px solid #c27b00;padding:.75rem 1rem;background:#fff6df}}
</style></head><body>
<h1>DiffeoForge modern workload plan</h1>
<p><strong>Project:</strong> {project}<br>
<strong>Config:</strong> {config_filename}<br>
<strong>Config SHA-256:</strong> <code>{source['sha256']}</code></p>
<div class="warning"><strong>Interpretation boundary:</strong> {boundary}</div>
<h2>Reviewed configuration</h2><ul>{reviewed_items}</ul>
<h2>Dense operation model</h2><ul>{operation_items}</ul>
<h2>Known payloads, not peak RAM</h2><ul>{payload_items}</ul>
<h2>Warnings</h2><ul>{warnings}</ul>
<h2>Input inventory</h2>
<table><thead><tr><th>File</th><th>Points</th><th>Triangles</th><th>Bytes</th></tr></thead><tbody>
{template_row}
{subject_rows}</tbody></table>
<p>Machine-readable values and exact formulas are stored in <code>{REPORT_JSON_NAME}</code>.</p>
</body></html>
"""


def _is_generated_report(directory: Path) -> bool:
    if not directory.is_dir():
        return False
    if {path.name for path in directory.iterdir()} != {REPORT_JSON_NAME, REPORT_HTML_NAME}:
        return False
    try:
        report = json.loads((directory / REPORT_JSON_NAME).read_text(encoding="utf-8"))
        first_line = (directory / REPORT_HTML_NAME).read_text(encoding="utf-8").splitlines()[0]
    except (OSError, UnicodeError, json.JSONDecodeError, IndexError):
        return False
    return report.get("workload_version") == WORKLOAD_VERSION and first_line == HTML_MARKER


def write_modern_workload_report(
    report: dict[str, Any],
    destination: Path | str,
    *,
    overwrite: bool = False,
) -> Path:
    """Atomically publish deterministic JSON and HTML in a dedicated directory."""

    output = Path(destination).expanduser().resolve()
    _validate_report(report)
    if output.exists() and not overwrite:
        raise FileExistsError(f"Modern workload report already exists: {output}")
    if output.exists() and not _is_generated_report(output):
        raise ModernWorkloadError(
            f"Refusing to replace a directory not recognized as a generated report: {output}"
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.parent / f".{output.name}.tmp-{uuid.uuid4().hex}"
    backup = output.parent / f".{output.name}.backup-{uuid.uuid4().hex}"
    temporary.mkdir()
    try:
        with (temporary / REPORT_JSON_NAME).open(
            "x", encoding="utf-8", newline="\n"
        ) as handle:
            json.dump(report, handle, indent=2, ensure_ascii=False, sort_keys=True)
            handle.write("\n")
        (temporary / REPORT_HTML_NAME).write_text(
            render_modern_workload_html(report),
            encoding="utf-8",
            newline="\n",
        )
        if output.exists():
            output.rename(backup)
        try:
            temporary.rename(output)
        except Exception:
            if backup.exists() and not output.exists():
                backup.rename(output)
            raise
        if backup.exists():
            # Publishing already succeeded. A transient cleanup problem must not
            # report the newly visible, valid output as a failed publication.
            shutil.rmtree(backup, ignore_errors=True)
    except Exception:
        if temporary.exists():
            shutil.rmtree(temporary)
        raise
    return output


def default_modern_workload_path(config_path: Path | str) -> Path:
    source = Path(config_path).expanduser().resolve()
    return source.with_suffix(".workload")


def plan_modern_workload(
    config_path: Path | str,
    *,
    destination: Path | str | None = None,
    overwrite: bool = False,
) -> Path:
    """Collect and atomically publish one pre-compute workload plan."""

    report = collect_modern_workload(config_path)
    output = (
        default_modern_workload_path(config_path) if destination is None else destination
    )
    return write_modern_workload_report(report, output, overwrite=overwrite)
