"""Auditable mesh-directory adapter for the experimental modern atlas engine."""

from __future__ import annotations

import csv
import json
import math
import os
import re
import shutil
import unicodedata
import uuid
from collections.abc import Mapping, Sequence
from datetime import UTC, datetime
from importlib.resources import files
from pathlib import Path, PurePosixPath
from typing import Any

import jsonschema
import numpy as np
import torch
import yaml

from diffeoforge import __version__
from diffeoforge.analysis.procrustes import generalized_procrustes
from diffeoforge.config import ConfigurationError, InputSummary, validate_input_paths
from diffeoforge.engine.atlas_optimizer import optimize_atlas
from diffeoforge.initialization import SUPPORTED_UNITS, detect_template
from diffeoforge.mesh import (
    MeshMetadata,
    TriangleMesh,
    inspect_inputs,
    inspect_vtk,
    read_vtk_polydata,
    sha256_file,
    write_vtk_polydata,
)
from diffeoforge.modern_bundle import (
    MANIFEST_NAME as BUNDLE_MANIFEST_NAME,
)
from diffeoforge.modern_bundle import (
    ModernAtlasModelSettings,
    verify_modern_atlas_bundle,
    write_modern_atlas_bundle,
)

WORKFLOW_VERSION = "0.1"
MANIFEST_NAME = "workflow-manifest.json"
MANIFEST_SIDECAR_NAME = "workflow-manifest.sha256"
CONFIG_MARKER = "# Generated by DiffeoForge modern-init; review every value before use."
LANDMARK_COLUMNS = ("mesh_file", "landmark", "x", "y", "z")
SCIENTIFIC_BOUNDARY = (
    "This experimental CPU/float64 workflow makes inputs, optional landmark alignment, "
    "initialization, optimization, and PCA artifacts auditable. It does not establish "
    "Deformetrica equivalence, biological validity, arbitrary-topology robustness, GPU "
    "parity, or production suitability for cohorts of 300 or more specimens."
)


class ModernWorkflowError(RuntimeError):
    """Raised when a modern workflow run cannot be created or verified safely."""


def _schema(name: str) -> dict[str, Any]:
    resource = files("diffeoforge.schema").joinpath(name)
    return json.loads(resource.read_text(encoding="utf-8"))


def _format_schema_error(error: jsonschema.ValidationError) -> str:
    location = ".".join(str(part) for part in error.absolute_path) or "<root>"
    return f"{location}: {error.message}"


def validate_modern_workflow_config(config: Mapping[str, Any]) -> None:
    """Validate a modern-workflow mapping against the bundled public schema."""

    validator = jsonschema.Draft202012Validator(_schema("modern-workflow-config-v0.1.json"))
    errors = sorted(validator.iter_errors(config), key=lambda error: list(error.absolute_path))
    if errors:
        details = "\n  - ".join(_format_schema_error(error) for error in errors)
        raise ConfigurationError(f"Modern workflow configuration validation failed:\n  - {details}")


def load_modern_workflow_config(path: Path | str) -> dict[str, Any]:
    """Load and validate one modern-workflow YAML configuration."""

    source = Path(path).expanduser().resolve()
    if not source.is_file():
        raise ConfigurationError(f"Modern workflow configuration does not exist: {source}")
    try:
        loaded = yaml.safe_load(source.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, yaml.YAMLError) as error:
        raise ConfigurationError(f"Could not read modern workflow YAML: {error}") from error
    if not isinstance(loaded, dict):
        raise ConfigurationError("Modern workflow configuration root must be a mapping.")
    validate_modern_workflow_config(loaded)
    return loaded


def _resolve_from_config(value: str, config_path: Path) -> Path:
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = config_path.parent / path
    return path.resolve()


def _portable_path(path: Path, base: Path) -> str:
    try:
        return path.resolve().relative_to(base.resolve()).as_posix()
    except ValueError:
        try:
            return Path(os.path.relpath(path.resolve(), base.resolve())).as_posix()
        except ValueError:
            return str(path.resolve())


def _resolve_template(directory: Path, template: Path | str | None) -> Path:
    if template is None:
        detected = detect_template(directory)
        if detected is None:
            raise ConfigurationError("No template.vtk was found; select the template explicitly.")
        return detected
    candidate = Path(template).expanduser()
    if not candidate.is_absolute():
        candidate = directory / candidate
    candidate = candidate.resolve()
    if not candidate.is_file():
        raise ConfigurationError(f"Template mesh does not exist: {candidate}")
    return candidate


def initialize_modern_workflow(
    mesh_directory: Path | str,
    *,
    units: str,
    config_path: Path | str = "modern-atlas.yaml",
    template: Path | str | None = None,
    subject_pattern: str = "*.vtk",
    project_name: str | None = None,
    output_directory: Path | str | None = None,
    landmarks_file: Path | str | None = None,
    control_point_count: int = 9,
    attachment_kernel_width: float | None = None,
    deformation_kernel_width: float | None = None,
    noise_variance: float | None = None,
    max_cycles: int = 3,
    threads: int | None = None,
    random_seed: int = 20260715,
    overwrite: bool = False,
) -> Path:
    """Inspect a mesh directory and write an explicit modern-workflow starter YAML."""

    directory = Path(mesh_directory).expanduser().resolve()
    if not directory.is_dir():
        raise ConfigurationError(f"Mesh directory does not exist: {directory}")
    if units not in SUPPORTED_UNITS:
        raise ConfigurationError(f"Unsupported coordinate unit: {units!r}")
    if isinstance(control_point_count, bool) or control_point_count < 1:
        raise ConfigurationError("control_point_count must be a positive integer")
    if isinstance(max_cycles, bool) or max_cycles < 0:
        raise ConfigurationError("max_cycles must be a nonnegative integer")
    thread_count = max(1, min(4, os.cpu_count() or 1)) if threads is None else threads
    if isinstance(thread_count, bool) or not isinstance(thread_count, int) or thread_count < 1:
        raise ConfigurationError("threads must be a positive integer")
    if isinstance(random_seed, bool) or not isinstance(random_seed, int) or random_seed < 0:
        raise ConfigurationError("random_seed must be a nonnegative integer")
    destination = Path(config_path).expanduser().resolve()
    if destination.exists():
        if not overwrite:
            raise ConfigurationError(
                f"Configuration already exists and will not be overwritten: {destination}"
            )
        try:
            first_line = destination.read_text(encoding="utf-8").splitlines()[0]
        except (OSError, UnicodeError, IndexError) as error:
            raise ConfigurationError(
                f"Could not verify existing configuration {destination}: {error}"
            ) from error
        if first_line != CONFIG_MARKER:
            raise ConfigurationError(
                "Refusing overwrite because the existing file is not a generated modern "
                f"workflow configuration: {destination}"
            )
    template_path = _resolve_template(directory, template)
    template_metadata = inspect_vtk(template_path)
    diagonal = template_metadata.bounding_box_diagonal

    def positive(name: str, value: float | None, fallback: float) -> float:
        result = fallback if value is None else value
        if isinstance(result, bool) or not isinstance(result, (int, float)):
            raise ConfigurationError(f"{name} must be a real scalar")
        normalized = float(result)
        if not math.isfinite(normalized) or normalized <= 0:
            raise ConfigurationError(f"{name} must be finite and greater than zero")
        return normalized

    config_base = destination.parent
    landmark_value: str | None = None
    landmark_source: Path | None = None
    if landmarks_file is not None:
        landmark_path = Path(landmarks_file).expanduser()
        if not landmark_path.is_absolute():
            landmark_path = directory / landmark_path
        landmark_path = landmark_path.resolve()
        if not landmark_path.is_file():
            raise ConfigurationError(f"Landmark CSV does not exist: {landmark_path}")
        landmark_source = landmark_path
        landmark_value = _portable_path(landmark_path, config_base)
    output_path = (
        (config_base / "modern-atlas-run").resolve()
        if output_directory is None
        else Path(output_directory).expanduser()
    )
    if not output_path.is_absolute():
        output_path = (config_base / output_path).resolve()
    default_name = (
        directory.parent.name
        if directory.name.casefold() in {"mesh", "meshes", "data"}
        else directory.name
    )
    config: dict[str, Any] = {
        "schema_version": WORKFLOW_VERSION,
        "project": {"name": project_name or f"{default_name}-modern-atlas"},
        "input": {
            "directory": _portable_path(directory, config_base),
            "subject_pattern": subject_pattern,
            "template": _portable_path(template_path, config_base),
            "units": units,
        },
        "preprocessing": {
            "procrustes": {
                "enabled": landmark_value is not None,
                "landmarks_file": landmark_value,
                "scale_to_unit_centroid_size": True,
                "allow_reflection": False,
                "tolerance": 1e-10,
                "max_iterations": 100,
            }
        },
        "initialization": {
            "control_points": {
                "method": "farthest_template_vertices",
                "count": int(control_point_count),
            },
            "momenta": "zeros",
        },
        "model": {
            "attachment": {
                "type": "current",
                "kernel_width": positive(
                    "attachment_kernel_width", attachment_kernel_width, 0.10 * diagonal
                ),
            },
            "deformation": {
                "kernel_width": positive(
                    "deformation_kernel_width", deformation_kernel_width, 0.15 * diagonal
                ),
                "timepoints": 10,
                "shooting_integrator": "rk2",
                "flow_integrator": "deformetrica_heun",
            },
            "noise_variance": positive("noise_variance", noise_variance, (0.025 * diagonal) ** 2),
        },
        "optimization": {
            "max_cycles": int(max_cycles),
            "block_order": ["momenta", "template", "control_points"],
            "momenta_step_size": 0.1,
            "template_step_size": 0.01,
            "control_points_step_size": 0.01,
            "backtracking_factor": 0.5,
            "armijo_constant": 0.0001,
            "gradient_tolerance": 1e-8,
            "minimum_step_size": 1e-12,
            "max_line_search_iterations": 20,
        },
        "analysis": {"pca_components": None},
        "runtime": {
            "device": "cpu",
            "precision": "float64",
            "threads": thread_count,
            "random_seed": random_seed,
        },
        "output": {"directory": _portable_path(output_path, config_base)},
    }
    validate_modern_workflow_config(config)
    summary = validate_input_paths(config, destination)
    inspect_inputs(summary)
    template_vertices = np.array(read_vtk_polydata(summary.template).vertices, dtype=np.float64)
    farthest_template_vertex_indices(template_vertices, control_point_count)
    if landmark_source is not None:
        _, landmark_values = _read_landmarks(
            landmark_source,
            (summary.template.name, *(path.name for path in summary.subjects)),
        )
        alignment = generalized_procrustes(
            landmark_values,
            scale_to_unit_centroid_size=True,
            allow_reflection=False,
            tolerance=1e-10,
            max_iterations=100,
        )
        if not alignment.converged:
            raise ConfigurationError(
                "Landmark Procrustes did not converge with the generated settings"
            )
    destination.parent.mkdir(parents=True, exist_ok=True)
    mode = "w" if overwrite else "x"
    try:
        with destination.open(mode, encoding="utf-8", newline="\n") as handle:
            handle.write(CONFIG_MARKER + "\n")
            handle.write(
                "# Geometry-scaled starter values are exploratory, not validated presets.\n"
            )
            yaml.safe_dump(config, handle, sort_keys=False, allow_unicode=True)
    except OSError as error:
        raise ConfigurationError(
            f"Could not write modern workflow configuration: {error}"
        ) from error
    return destination


def _write_json_exclusive(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x", encoding="utf-8", newline="\n") as handle:
        json.dump(value, handle, indent=2, sort_keys=True, ensure_ascii=False, allow_nan=False)
        handle.write("\n")


def _copy_exclusive(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with source.open("rb") as input_handle, destination.open("xb") as output_handle:
        shutil.copyfileobj(input_handle, output_handle)
    if sha256_file(source) != sha256_file(destination):
        raise ModernWorkflowError(f"Copied input checksum mismatch: {source.name}")


def _slug(value: str) -> str:
    ascii_value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode()
    normalized = re.sub(r"[^A-Za-z0-9._-]+", "-", ascii_value).strip("-._").lower()
    return normalized or "mesh"


def _timestamp(value: str | None) -> str:
    timestamp = datetime.now(UTC).isoformat(timespec="seconds") if value is None else value
    if not isinstance(timestamp, str) or not timestamp.strip():
        raise ValueError("created_at must be a non-empty string")
    try:
        parsed = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
    except ValueError as error:
        raise ValueError("created_at must be an ISO-8601 timestamp") from error
    if parsed.tzinfo is None:
        raise ValueError("created_at must include a timezone offset")
    return timestamp.strip()


def _read_landmarks(
    path: Path,
    mesh_files: Sequence[str],
) -> tuple[tuple[str, ...], np.ndarray]:
    expected = tuple(mesh_files)
    if len(set(expected)) != len(expected):
        raise ConfigurationError("Landmark mesh filenames are not unique")
    rows: dict[str, list[tuple[str, tuple[float, float, float]]]] = {name: [] for name in expected}
    try:
        with path.open(encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            if tuple(reader.fieldnames or ()) != LANDMARK_COLUMNS:
                raise ConfigurationError(
                    "Landmark CSV header must be exactly: " + ",".join(LANDMARK_COLUMNS)
                )
            for line_number, row in enumerate(reader, start=2):
                if None in row:
                    raise ConfigurationError(
                        f"Landmark CSV row {line_number} has unexpected extra columns"
                    )
                mesh_file = (row["mesh_file"] or "").strip()
                label = (row["landmark"] or "").strip()
                if mesh_file not in rows:
                    raise ConfigurationError(
                        f"Landmark CSV row {line_number} names unknown mesh {mesh_file!r}"
                    )
                if not label:
                    raise ConfigurationError(
                        f"Landmark CSV row {line_number} has an empty landmark label"
                    )
                if any(existing[0] == label for existing in rows[mesh_file]):
                    raise ConfigurationError(
                        f"Landmark {label!r} is duplicated for mesh {mesh_file!r}"
                    )
                try:
                    coordinates = tuple(float(row[axis]) for axis in ("x", "y", "z"))
                except (TypeError, ValueError) as error:
                    raise ConfigurationError(
                        f"Landmark CSV row {line_number} contains non-numeric coordinates"
                    ) from error
                if not all(math.isfinite(value) for value in coordinates):
                    raise ConfigurationError(
                        f"Landmark CSV row {line_number} contains non-finite coordinates"
                    )
                rows[mesh_file].append((label, coordinates))
    except OSError as error:
        raise ConfigurationError(f"Could not read landmark CSV {path}: {error}") from error

    first_labels = tuple(label for label, _ in rows[expected[0]])
    if len(first_labels) < 3:
        raise ConfigurationError("Landmark CSV requires at least three landmarks per mesh")
    for mesh_file in expected:
        labels = tuple(label for label, _ in rows[mesh_file])
        if labels != first_labels:
            raise ConfigurationError(
                "Every mesh must use the same unique landmark labels in the same row order; "
                f"mismatch at {mesh_file!r}"
            )
    values = np.array(
        [[coordinates for _, coordinates in rows[mesh_file]] for mesh_file in expected],
        dtype=np.float64,
    )
    return first_labels, values


def farthest_template_vertex_indices(vertices: np.ndarray, count: int) -> tuple[int, ...]:
    """Select deterministic well-spread template vertices without hidden randomness."""

    if not isinstance(vertices, np.ndarray) or vertices.dtype != np.float64:
        raise TypeError("vertices must be a numpy.float64 array")
    if vertices.ndim != 2 or vertices.shape[1] != 3 or vertices.shape[0] == 0:
        raise ValueError("vertices must have shape (points, 3)")
    if not bool(np.isfinite(vertices).all()):
        raise ValueError("vertices must contain only finite coordinates")
    if isinstance(count, bool) or not isinstance(count, int) or count < 1:
        raise TypeError("count must be a positive integer")
    unique_count = np.unique(vertices, axis=0).shape[0]
    if count > unique_count:
        raise ValueError(
            f"control-point count {count} exceeds {unique_count} unique template vertices"
        )
    centroid = np.mean(vertices, axis=0)
    selected = [int(np.argmax(np.sum((vertices - centroid) ** 2, axis=1)))]
    minimum_squared = np.sum((vertices - vertices[selected[0]]) ** 2, axis=1)
    chosen = np.zeros(vertices.shape[0], dtype=bool)
    chosen[selected[0]] = True
    while len(selected) < count:
        candidates = minimum_squared.copy()
        candidates[chosen] = -1.0
        next_index = int(np.argmax(candidates))
        if candidates[next_index] <= 0:
            raise ValueError("template does not contain enough distinct control-point locations")
        selected.append(next_index)
        chosen[next_index] = True
        minimum_squared = np.minimum(
            minimum_squared,
            np.sum((vertices - vertices[next_index]) ** 2, axis=1),
        )
    return tuple(selected)


def _mesh_record(
    *,
    index: int,
    label: str,
    source: Path,
    raw_path: Path,
    aligned_path: Path | None,
    metadata: MeshMetadata,
    root: Path,
) -> dict[str, Any]:
    return {
        "index": index,
        "label": label,
        "source_filename": source.name,
        "raw_path": raw_path.relative_to(root).as_posix(),
        "aligned_path": (
            None if aligned_path is None else aligned_path.relative_to(root).as_posix()
        ),
        "bytes": metadata.bytes,
        "sha256": metadata.sha256,
        "points": metadata.points,
        "triangles": metadata.cells,
    }


def _artifact(root: Path, path: Path) -> dict[str, Any]:
    return {
        "path": path.relative_to(root).as_posix(),
        "bytes": path.stat().st_size,
        "sha256": sha256_file(path),
    }


def _validate_run_manifest(manifest: dict[str, Any]) -> None:
    try:
        jsonschema.Draft202012Validator(_schema("modern-workflow-run-v0.1.json")).validate(manifest)
    except jsonschema.ValidationError as error:
        raise ModernWorkflowError(
            f"Modern workflow manifest schema validation failed at {_format_schema_error(error)}"
        ) from error


def _alignment_evidence(
    root: Path,
    config_path: Path,
    procrustes: Mapping[str, Any],
    source_paths: tuple[Path, ...],
    raw_paths: tuple[Path, ...],
    geometries: tuple[TriangleMesh, ...],
) -> tuple[
    tuple[np.ndarray, ...],
    tuple[Path, ...],
    dict[str, Any],
]:
    landmark_source = _resolve_from_config(procrustes["landmarks_file"], config_path)
    if not landmark_source.is_file():
        raise ConfigurationError(f"Landmark CSV does not exist: {landmark_source}")
    landmark_copy = root / "input" / "landmarks.csv"
    _copy_exclusive(landmark_source, landmark_copy)
    landmark_labels, landmarks = _read_landmarks(
        landmark_copy, tuple(path.name for path in source_paths)
    )
    result = generalized_procrustes(
        landmarks,
        scale_to_unit_centroid_size=procrustes["scale_to_unit_centroid_size"],
        allow_reflection=procrustes["allow_reflection"],
        tolerance=procrustes["tolerance"],
        max_iterations=procrustes["max_iterations"],
    )
    if not result.converged:
        raise ModernWorkflowError(
            "Generalized Procrustes did not converge; no atlas run was published"
        )
    aligned_vertices: list[np.ndarray] = []
    aligned_paths: list[Path] = []
    specimens: list[dict[str, Any]] = []
    for index, (source, raw_path, geometry, transform) in enumerate(
        zip(source_paths, raw_paths, geometries, result.transforms, strict=True)
    ):
        vertices = transform.apply(np.array(geometry.vertices, dtype=np.float64))
        aligned_path = root / "input" / "aligned" / f"mesh-{index:04d}-{_slug(source.stem)}.vtk"
        write_vtk_polydata(
            aligned_path,
            vertices.tolist(),
            geometry.triangles,
            title=f"DiffeoForge aligned mesh {index:04d}",
        )
        aligned_vertices.append(vertices)
        aligned_paths.append(aligned_path)
        specimens.append(
            {
                "index": index,
                "mesh_file": source.name,
                "raw_path": raw_path.relative_to(root).as_posix(),
                "aligned_path": aligned_path.relative_to(root).as_posix(),
                "residual": result.residuals[index],
                "transform": {
                    "centroid": transform.centroid.tolist(),
                    "scale": transform.scale,
                    "rotation": transform.rotation.tolist(),
                },
            }
        )
    evidence = {
        "alignment_version": "0.1",
        "method": "generalized_procrustes",
        "coordinate_convention": "aligned = ((raw - centroid) * scale) @ rotation",
        "landmark_columns": list(LANDMARK_COLUMNS),
        "landmark_labels": list(landmark_labels),
        "settings": {
            "scale_to_unit_centroid_size": result.scale_to_unit_centroid_size,
            "allow_reflection": result.allow_reflection,
            "tolerance": float(procrustes["tolerance"]),
            "max_iterations": int(procrustes["max_iterations"]),
        },
        "converged": result.converged,
        "termination_reason": result.termination_reason,
        "consensus": result.mean_shape.tolist(),
        "history": [
            {
                "iteration": item.iteration,
                "mean_change": item.mean_change,
                "total_squared_residual": item.total_squared_residual,
            }
            for item in result.history
        ],
        "specimens": specimens,
    }
    alignment_path = root / "preprocessing" / "procrustes.json"
    _write_json_exclusive(alignment_path, evidence)
    manifest = {
        "id": "generalized_procrustes",
        "landmarks_path": landmark_copy.relative_to(root).as_posix(),
        "alignment_path": alignment_path.relative_to(root).as_posix(),
        "converged": result.converged,
        "termination_reason": result.termination_reason,
    }
    return tuple(aligned_vertices), tuple(aligned_paths), manifest


def run_modern_workflow(
    config_path: Path | str,
    *,
    destination: Path | str | None = None,
    created_at: str | None = None,
) -> Path:
    """Atomically execute a configured mesh-folder workflow and publish its evidence."""

    source_config = Path(config_path).expanduser().resolve()
    config = load_modern_workflow_config(source_config)
    inputs: InputSummary = validate_input_paths(config, source_config)
    template_metadata, subject_metadata = inspect_inputs(inputs)
    output = (
        _resolve_from_config(config["output"]["directory"], source_config)
        if destination is None
        else Path(destination).expanduser().resolve()
    )
    if output.exists():
        raise FileExistsError(f"Modern workflow destination already exists: {output}")
    timestamp = _timestamp(created_at)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.parent / f".{output.name}.tmp-{uuid.uuid4().hex}"
    temporary.mkdir()
    previous_threads = torch.get_num_threads()
    try:
        source_copy = temporary / "config" / "source.yaml"
        _copy_exclusive(source_config, source_copy)
        effective_path = temporary / "config" / "effective-config.json"
        _write_json_exclusive(effective_path, config)

        source_paths = (inputs.template, *inputs.subjects)
        raw_paths: list[Path] = []
        for index, source in enumerate(source_paths):
            role = "template" if index == 0 else "subject"
            raw_path = temporary / "input" / "raw" / f"{role}-{index:04d}-{_slug(source.stem)}.vtk"
            _copy_exclusive(source, raw_path)
            raw_paths.append(raw_path)
        raw_path_tuple = tuple(raw_paths)
        geometries = tuple(read_vtk_polydata(path) for path in raw_path_tuple)

        procrustes = config["preprocessing"]["procrustes"]
        if procrustes["enabled"]:
            vertices, aligned_paths, preprocessing = _alignment_evidence(
                temporary,
                source_config,
                procrustes,
                source_paths,
                raw_path_tuple,
                geometries,
            )
        else:
            vertices = tuple(
                np.array(geometry.vertices, dtype=np.float64) for geometry in geometries
            )
            aligned_paths = tuple(None for _ in geometries)
            preprocessing = {
                "id": "none",
                "landmarks_path": None,
                "alignment_path": None,
                "converged": None,
                "termination_reason": None,
            }

        count = config["initialization"]["control_points"]["count"]
        control_indices = farthest_template_vertex_indices(vertices[0], count)
        template_tensor = torch.tensor(vertices[0], dtype=torch.float64)
        triangle_tensor = torch.tensor(geometries[0].triangles, dtype=torch.int64)
        target_tensors = tuple(
            (
                torch.tensor(subject_vertices, dtype=torch.float64),
                torch.tensor(geometry.triangles, dtype=torch.int64),
            )
            for subject_vertices, geometry in zip(vertices[1:], geometries[1:], strict=True)
        )
        control_points = template_tensor[list(control_indices)].clone()
        momenta = torch.zeros(
            (len(target_tensors), control_points.shape[0], 3), dtype=torch.float64
        )
        model = config["model"]
        deformation = model["deformation"]
        attachment = model["attachment"]
        optimizer = config["optimization"]
        runtime = config["runtime"]
        torch.set_num_threads(runtime["threads"])
        if torch.get_num_threads() != runtime["threads"]:
            raise ModernWorkflowError("PyTorch did not apply the requested CPU thread count")
        with torch.random.fork_rng(devices=[]):
            torch.manual_seed(runtime["random_seed"])
            result = optimize_atlas(
                template_tensor,
                triangle_tensor,
                target_tensors,
                control_points,
                momenta,
                deformation_kernel_width=deformation["kernel_width"],
                attachment_kernel_width=attachment["kernel_width"],
                noise_variance=model["noise_variance"],
                number_of_time_points=deformation["timepoints"],
                attachment_type=attachment["type"],
                shooting_integrator=deformation["shooting_integrator"],
                flow_integrator=deformation["flow_integrator"],
                max_cycles=optimizer["max_cycles"],
                block_order=optimizer["block_order"],
                momenta_step_size=optimizer["momenta_step_size"],
                template_step_size=optimizer["template_step_size"],
                control_points_step_size=optimizer["control_points_step_size"],
                backtracking_factor=optimizer["backtracking_factor"],
                armijo_constant=optimizer["armijo_constant"],
                gradient_tolerance=optimizer["gradient_tolerance"],
                minimum_step_size=optimizer["minimum_step_size"],
                max_line_search_iterations=optimizer["max_line_search_iterations"],
            )
        model_settings = ModernAtlasModelSettings(
            deformation_kernel_width=deformation["kernel_width"],
            attachment_kernel_width=attachment["kernel_width"],
            noise_variance=model["noise_variance"],
            number_of_time_points=deformation["timepoints"],
            attachment_type=attachment["type"],
            shooting_integrator=deformation["shooting_integrator"],
            flow_integrator=deformation["flow_integrator"],
        )
        bundle_path = write_modern_atlas_bundle(
            temporary / "result" / "atlas-bundle",
            result,
            triangle_tensor,
            [path.name for path in inputs.subjects],
            model_settings,
            pca_components=config["analysis"]["pca_components"],
            created_at=timestamp,
        )
        bundle_manifest = verify_modern_atlas_bundle(bundle_path)

        template_record = _mesh_record(
            index=0,
            label=inputs.template.name,
            source=inputs.template,
            raw_path=raw_path_tuple[0],
            aligned_path=aligned_paths[0],
            metadata=template_metadata,
            root=temporary,
        )
        subject_records = [
            _mesh_record(
                index=index,
                label=source.name,
                source=source,
                raw_path=raw_path,
                aligned_path=aligned_path,
                metadata=mesh_metadata,
                root=temporary,
            )
            for index, (source, raw_path, aligned_path, mesh_metadata) in enumerate(
                zip(
                    inputs.subjects,
                    raw_path_tuple[1:],
                    aligned_paths[1:],
                    subject_metadata,
                    strict=True,
                )
            )
        ]
        artifact_paths = sorted(path for path in temporary.rglob("*") if path.is_file())
        artifacts = [_artifact(temporary, path) for path in artifact_paths]
        manifest = {
            "workflow_version": WORKFLOW_VERSION,
            "created_at": timestamp,
            "project": {"name": config["project"]["name"]},
            "engine": {
                "id": "diffeoforge_modern_dense",
                "diffeoforge": __version__,
                "pytorch": torch.__version__,
                "numpy": np.__version__,
                "device": "cpu",
                "dtype": "float64",
                "threads": runtime["threads"],
                "random_seed": runtime["random_seed"],
            },
            "config": {
                "source_path": source_copy.relative_to(temporary).as_posix(),
                "effective_path": effective_path.relative_to(temporary).as_posix(),
            },
            "input": {
                "units": config["input"]["units"],
                "subject_pattern": config["input"]["subject_pattern"],
                "template": template_record,
                "subjects": subject_records,
            },
            "preprocessing": preprocessing,
            "initialization": {
                "control_points": {
                    "method": "farthest_template_vertices",
                    "count": len(control_indices),
                    "template_vertex_indices": list(control_indices),
                },
                "momenta": "zeros",
            },
            "result_bundle": {
                "path": bundle_path.relative_to(temporary).as_posix(),
                "bundle_version": bundle_manifest["bundle_version"],
                "manifest_sha256": sha256_file(bundle_path / BUNDLE_MANIFEST_NAME),
            },
            "artifacts": artifacts,
            "scientific_boundary": SCIENTIFIC_BOUNDARY,
            "immutability_contract": {
                "creation": "atomic rename into a previously nonexistent destination",
                "manifest": "SHA-256 sidecar",
                "artifacts": "all listed files require matching byte size and SHA-256",
                "extra_files": "verification failure",
                "signature": "not cryptographically signed",
            },
        }
        _validate_run_manifest(manifest)
        manifest_path = temporary / MANIFEST_NAME
        _write_json_exclusive(manifest_path, manifest)
        sidecar = temporary / MANIFEST_SIDECAR_NAME
        with sidecar.open("x", encoding="ascii", newline="\n") as handle:
            handle.write(f"{sha256_file(manifest_path)}  {MANIFEST_NAME}\n")
        verify_modern_workflow(temporary)
        if output.exists():
            raise FileExistsError(f"Modern workflow destination appeared during creation: {output}")
        temporary.rename(output)
    except Exception:
        if temporary.exists():
            shutil.rmtree(temporary)
        raise
    finally:
        torch.set_num_threads(previous_threads)
    return output


def _read_json_object(path: Path, label: str) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ModernWorkflowError(f"{label} is not readable JSON: {path}") from error
    if not isinstance(value, dict):
        raise ModernWorkflowError(f"{label} must be a JSON object: {path}")
    return value


def _resolve_artifact(root: Path, value: object, *, directory: bool = False) -> Path:
    if not isinstance(value, str) or not value or "\\" in value:
        raise ModernWorkflowError("Workflow artifact paths must be POSIX-style strings")
    relative = PurePosixPath(value)
    if (
        relative.is_absolute()
        or ".." in relative.parts
        or "." in relative.parts
        or (relative.parts and ":" in relative.parts[0])
    ):
        raise ModernWorkflowError(f"Unsafe workflow artifact path: {value!r}")
    path = root.joinpath(*relative.parts)
    try:
        path.resolve().relative_to(root.resolve())
    except ValueError as error:
        raise ModernWorkflowError(f"Workflow artifact escapes the run: {value!r}") from error
    valid = path.is_dir() if directory else path.is_file()
    if not valid:
        kind = "directory" if directory else "file"
        raise ModernWorkflowError(f"Workflow artifact {kind} is missing: {value}")
    return path


def verify_modern_workflow(directory: Path | str) -> dict[str, Any]:
    """Verify schema, exact inventory, copied geometry, and the nested atlas bundle."""

    root = Path(directory).expanduser().resolve()
    if not root.is_dir():
        raise ModernWorkflowError(f"Modern workflow directory does not exist: {root}")
    for path in root.rglob("*"):
        if path.is_symlink():
            raise ModernWorkflowError(f"Workflow runs must not contain symbolic links: {path}")
    manifest_path = root / MANIFEST_NAME
    manifest = _read_json_object(manifest_path, "Modern workflow manifest")
    _validate_run_manifest(manifest)
    sidecar_path = root / MANIFEST_SIDECAR_NAME
    try:
        sidecar = sidecar_path.read_text(encoding="ascii")
    except (OSError, UnicodeError) as error:
        raise ModernWorkflowError("Modern workflow manifest sidecar is unreadable") from error
    expected_sidecar = f"{sha256_file(manifest_path)}  {MANIFEST_NAME}\n"
    if sidecar != expected_sidecar:
        raise ModernWorkflowError("Modern workflow manifest SHA-256 sidecar does not match")

    records = manifest["artifacts"]
    listed = [record["path"] for record in records]
    if len(listed) != len(set(listed)):
        raise ModernWorkflowError("Modern workflow artifact inventory contains duplicate paths")
    actual = set()
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        if relative not in {MANIFEST_NAME, MANIFEST_SIDECAR_NAME}:
            actual.add(relative)
    if actual != set(listed):
        missing = sorted(set(listed) - actual)
        extra = sorted(actual - set(listed))
        raise ModernWorkflowError(
            f"Modern workflow exact file inventory differs; missing={missing}, extra={extra}"
        )
    for record in records:
        path = _resolve_artifact(root, record["path"])
        if path.stat().st_size != record["bytes"]:
            raise ModernWorkflowError(f"Workflow artifact size differs: {record['path']}")
        if sha256_file(path) != record["sha256"]:
            raise ModernWorkflowError(f"Workflow artifact SHA-256 differs: {record['path']}")

    effective_path = _resolve_artifact(root, manifest["config"]["effective_path"])
    effective = _read_json_object(effective_path, "Effective workflow configuration")
    try:
        validate_modern_workflow_config(effective)
    except ConfigurationError as error:
        raise ModernWorkflowError(str(error)) from error
    _resolve_artifact(root, manifest["config"]["source_path"])

    mesh_records = [manifest["input"]["template"], *manifest["input"]["subjects"]]
    for record in mesh_records:
        raw = _resolve_artifact(root, record["raw_path"])
        metadata = inspect_vtk(raw)
        if (
            metadata.bytes != record["bytes"]
            or metadata.sha256 != record["sha256"]
            or metadata.points != record["points"]
            or metadata.cells != record["triangles"]
        ):
            raise ModernWorkflowError(
                f"Copied raw mesh metadata differs for {record['source_filename']!r}"
            )
        aligned_value = record["aligned_path"]
        if aligned_value is not None:
            aligned = inspect_vtk(_resolve_artifact(root, aligned_value))
            if aligned.points != record["points"] or aligned.cells != record["triangles"]:
                raise ModernWorkflowError(
                    f"Aligned mesh geometry count differs for {record['source_filename']!r}"
                )

    preprocessing = manifest["preprocessing"]
    if preprocessing["id"] == "none":
        if any(record["aligned_path"] is not None for record in mesh_records):
            raise ModernWorkflowError("Unaligned workflow unexpectedly lists aligned mesh paths")
    else:
        _resolve_artifact(root, preprocessing["landmarks_path"])
        alignment_path = _resolve_artifact(root, preprocessing["alignment_path"])
        alignment = _read_json_object(alignment_path, "Procrustes evidence")
        if alignment.get("converged") is not True:
            raise ModernWorkflowError("Published Procrustes evidence is not converged")
        if len(alignment.get("specimens", [])) != len(mesh_records):
            raise ModernWorkflowError("Procrustes evidence specimen count differs")

    control = manifest["initialization"]["control_points"]
    if control["count"] != len(control["template_vertex_indices"]):
        raise ModernWorkflowError("Control-point count differs from stored vertex indices")
    if max(control["template_vertex_indices"]) >= manifest["input"]["template"]["points"]:
        raise ModernWorkflowError("Control-point initialization index is out of range")

    bundle = _resolve_artifact(root, manifest["result_bundle"]["path"], directory=True)
    bundle_manifest = verify_modern_atlas_bundle(bundle)
    if bundle_manifest["bundle_version"] != manifest["result_bundle"]["bundle_version"]:
        raise ModernWorkflowError("Nested atlas bundle version differs")
    if sha256_file(bundle / BUNDLE_MANIFEST_NAME) != manifest["result_bundle"]["manifest_sha256"]:
        raise ModernWorkflowError("Nested atlas bundle manifest SHA-256 differs")
    if len(bundle_manifest["subjects"]) != len(manifest["input"]["subjects"]):
        raise ModernWorkflowError("Nested atlas bundle subject count differs")
    return manifest
