"""Read-only exact plan for one future immutable reference-run preparation."""

from __future__ import annotations

import hashlib
import html
import json
import os
import platform
from collections.abc import Mapping
from importlib.resources import files
from io import StringIO
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft202012Validator

from diffeoforge import __version__
from diffeoforge.backends import (
    BACKEND_CONTRACT_VERSION,
    BACKEND_ID,
    ENGINE_CONSTANTS,
    build_command,
    render_engine_file_bytes,
    validate_reference_config,
)
from diffeoforge.config import (
    ConfigurationError,
    load_config,
    resolve_output_directory,
    validate_input_paths,
)
from diffeoforge.mesh import inspect_inputs, sha256_file
from diffeoforge.runs import (
    effective_reference_config,
    normalize_run_id,
    reference_input_record,
)

SCHEMA_VERSION = "0.1"
STATUS = "read_only_plan_not_prepared"
SCIENTIFIC_BOUNDARY = (
    "This deterministic plan describes bytes and paths that DiffeoForge would use for "
    "one immutable Deformetrica reference-run preparation. It creates no directory, "
    "copies no mesh, launches no process, and does not validate parameter choice, "
    "registration quality, numerical convergence, or biological interpretation."
)
PLANNED_DIRECTORIES = (
    "config",
    "engine",
    "input/template",
    "input/subjects",
    "logs",
    "output",
)
HTML_MARKER = (
    "<!-- Generated by DiffeoForge reference-plan; immutable review copy. -->"
)


def _schema() -> Mapping[str, Any]:
    resource = files("diffeoforge.schema").joinpath(
        "reference-preparation-plan-v0.1.json"
    )
    return json.loads(resource.read_text(encoding="utf-8"))


def _validate_plan(plan: Mapping[str, Any]) -> None:
    validator = Draft202012Validator(_schema())
    errors = sorted(validator.iter_errors(plan), key=lambda error: list(error.path))
    if not errors:
        return
    first = errors[0]
    location = ".".join(str(part) for part in first.path) or "<root>"
    raise ConfigurationError(
        f"Reference preparation plan schema violation at {location}: {first.message}"
    )


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _format_bytes(value: int) -> str:
    if value < 1024:
        return f"{value} B"
    if value < 1024**2:
        return f"{value / 1024:.1f} KiB"
    if value < 1024**3:
        return f"{value / 1024**2:.1f} MiB"
    return f"{value / 1024**3:.2f} GiB"


def reference_preparation_plan_fingerprint(plan: Mapping[str, Any]) -> str:
    """Hash the canonical, ASCII-safe machine-readable plan representation."""

    _validate_plan(plan)
    payload = json.dumps(
        plan,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("ascii")
    return _sha256_bytes(payload)


def render_reference_preparation_plan_html(plan: Mapping[str, Any]) -> str:
    """Render a deterministic offline review page from one validated plan."""

    _validate_plan(plan)
    escape = html.escape
    run = plan["run"]
    source = plan["source_config"]
    backend = plan["backend"]
    planner = plan["planner"]
    command = plan["command_preview"]
    fingerprint = reference_preparation_plan_fingerprint(plan)

    input_rows = "".join(
        "<tr>"
        f"<td>{escape(str(item['role']))}</td>"
        f"<td><code>{escape(str(item['source_path']))}</code></td>"
        f"<td><code>{escape(str(item['staged_path']))}</code></td>"
        f"<td>{int(item['geometry']['points']):,}</td>"
        f"<td>{int(item['geometry']['cells']):,}</td>"
        f"<td>{_format_bytes(int(item['geometry']['bytes']))}</td>"
        f"<td><code>{escape(str(item['geometry']['sha256']))}</code></td>"
        "</tr>"
        for item in plan["inputs"]
    )
    protected_rows = "".join(
        "<tr>"
        f"<td>{index}</td>"
        f"<td>{escape(str(item['kind']))}</td>"
        f"<td><code>{escape(str(item['path']))}</code></td>"
        f"<td>{_format_bytes(int(item['bytes']))}</td>"
        f"<td><code>{escape(str(item['sha256']))}</code></td>"
        "</tr>"
        for index, item in enumerate(plan["protected_files"], start=1)
    )
    generated_sections = "".join(
        "<details>"
        f"<summary><code>{escape(str(item['path']))}</code> "
        f"({_format_bytes(int(item['bytes']))})</summary>"
        f"<pre>{escape(str(item['content_utf8']))}</pre>"
        "</details>"
        for item in plan["protected_files"]
        if item["kind"] == "generated"
    )
    directory_items = "".join(
        f"<li><code>{escape(str(directory))}</code></li>"
        for directory in plan["directories"]
    )
    argument_items = "".join(
        f"<li><code>{escape(str(value))}</code></li>" for value in command["argv"]
    )
    environment_rows = "".join(
        f"<tr><td><code>{escape(str(name))}</code></td>"
        f"<td><code>{escape(str(value))}</code></td></tr>"
        for name, value in sorted(command["environment"].items())
    )
    constant_rows = "".join(
        f"<tr><td><code>{escape(str(name))}</code></td>"
        f"<td><code>{escape(str(value))}</code></td></tr>"
        for name, value in sorted(backend["engine_constants"].items())
    )

    return f"""{HTML_MARKER}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="generator" content="DiffeoForge reference preparation plan">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DiffeoForge reference preparation plan - {escape(str(run['run_id']))}</title>
  <style>
    :root {{ color-scheme: light; --ink: #17202a; --muted: #52606d; --line: #ccd6df;
      --panel: #f5f8fa; --accent: #174f78; --warn: #744b00; --warn-bg: #fff3cd;
      --safe: #0d6338; --safe-bg: #e4f5eb; }}
    * {{ box-sizing: border-box; }}
    body {{ margin: 0; color: var(--ink); font: 15px/1.5 system-ui, sans-serif; }}
    main {{ max-width: 1240px; margin: 0 auto; padding: 2rem; }}
    h1 {{ margin: .35rem 0; }} h2 {{ margin-top: 2.2rem; color: var(--accent); }}
    code, pre {{ font-family: ui-monospace, SFMono-Regular, Consolas, monospace; }}
    code {{ overflow-wrap: anywhere; }}
    .status {{ display: inline-block; border-radius: 999px; padding: .35rem .75rem;
      color: var(--safe); background: var(--safe-bg); font-weight: 750; }}
    .boundary, .privacy {{ border-left: .4rem solid var(--warn); padding: .9rem 1rem;
      background: var(--warn-bg); }}
    .cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
      gap: .8rem; margin: 1rem 0; }}
    .card {{ border: 1px solid var(--line); border-radius: .55rem; padding: 1rem;
      background: var(--panel); }}
    .card strong {{ display: block; margin-top: .2rem; font-size: 1.25rem; }}
    table {{ width: 100%; border-collapse: collapse; font-size: .9rem; }}
    th, td {{ border: 1px solid var(--line); padding: .5rem; text-align: left;
      vertical-align: top; }} th {{ background: var(--panel); }}
    .scroll {{ overflow-x: auto; }}
    pre {{ white-space: pre-wrap; overflow-wrap: anywhere; padding: 1rem; border-radius: .45rem;
      color: #edf2f7; background: #111820; }}
    details {{ border: 1px solid var(--line); border-radius: .45rem; padding: .65rem;
      margin: .65rem 0; }} summary {{ cursor: pointer; font-weight: 650; }}
    footer {{ margin-top: 2.5rem; padding-top: 1rem; border-top: 1px solid var(--line);
      color: var(--muted); }}
  </style>
</head>
<body><main>
  <header>
    <span class="status">Review only - destination absent - nothing prepared</span>
    <h1>Reference preparation plan</h1>
    <p>Run ID <code>{escape(str(run['run_id']))}</code> for backend
      <code>{escape(str(backend['id']))}</code>.</p>
  </header>

  <div class="boundary"><strong>Scientific and lifecycle boundary:</strong>
    {escape(str(plan['scientific_boundary']))}</div>
  <p class="privacy"><strong>Privacy:</strong> This report contains full local paths and specimen
    filenames. Review them before sharing the file.</p>

  <section>
    <h2>Plan identity</h2>
    <div class="cards">
      <div class="card">Subjects<strong>{int(plan['input_count']['subjects']):,}</strong></div>
      <div class="card">Protected files<strong>{int(plan['protected_file_count']):,}</strong></div>
      <div class="card">Protected payload
        <strong>{_format_bytes(int(plan['total_protected_bytes']))}</strong></div>
      <div class="card">Native XML newlines
        <strong>{escape(str(planner['native_newline']))}</strong></div>
    </div>
    <p><strong>Plan schema:</strong> <code>{escape(str(plan['schema_version']))}</code><br>
      <strong>Status:</strong> <code>{escape(str(plan['status']))}</code><br>
      <strong>Canonical plan SHA-256:</strong> <code>{fingerprint}</code><br>
      <strong>Source config:</strong> <code>{escape(str(source['path']))}</code><br>
      <strong>Source config SHA-256:</strong> <code>{escape(str(source['sha256']))}</code><br>
      <strong>Output root:</strong> <code>{escape(str(run['output_root']))}</code><br>
      <strong>Future destination:</strong> <code>{escape(str(run['destination']))}</code></p>
  </section>

  <section>
    <h2>Planner and backend contract</h2>
    <p><strong>DiffeoForge:</strong> <code>{escape(str(planner['diffeoforge']))}</code><br>
      <strong>Python:</strong> <code>{escape(str(planner['python']))}</code><br>
      <strong>Platform:</strong> <code>{escape(str(planner['platform']))}</code><br>
      <strong>Backend contract:</strong> <code>{escape(str(backend['contract_version']))}</code></p>
    <table><thead><tr><th>Fixed engine constant</th><th>Value</th></tr></thead>
      <tbody>{constant_rows}</tbody></table>
  </section>

  <section><h2>Planned directories</h2><ol>{directory_items}</ol></section>

  <section>
    <h2>Exact input inventory</h2>
    <div class="scroll"><table>
      <thead><tr><th>Role</th><th>Source</th><th>Future staged path</th><th>Points</th>
        <th>Cells</th><th>Bytes</th><th>SHA-256</th></tr></thead>
      <tbody>{input_rows}</tbody>
    </table></div>
  </section>

  <section>
    <h2>Future protected-file inventory</h2>
    <p>Order, paths, byte counts, and hashes match the independent preparation path.</p>
    <div class="scroll"><table>
      <thead><tr><th>#</th><th>Kind</th><th>Future relative path</th><th>Bytes</th>
        <th>SHA-256</th></tr></thead>
      <tbody>{protected_rows}</tbody>
    </table></div>
  </section>

  <section>
    <h2>Exact generated UTF-8 files</h2>
    <p>These are the effective YAML and engine XML bytes that preparation would write.</p>
    {generated_sections}
  </section>

  <section>
    <h2>Command preview</h2>
    <p><strong>Working directory:</strong>
      <code>{escape(str(command['working_directory']))}</code></p>
    <p>Argument vector in exact order:</p><ol>{argument_items}</ol>
    <table><thead><tr><th>Controlled environment name</th><th>Value</th></tr></thead>
      <tbody>{environment_rows}</tbody></table>
  </section>

  <footer>Deterministic offline DiffeoForge review page - no JavaScript, network calls,
    external assets, preparation, or engine launch.</footer>
</main></body></html>
"""


def write_reference_preparation_plan_report(
    plan: Mapping[str, Any],
    output_path: Path | str,
) -> Path:
    """Exclusively write one review report without replacing any existing path."""

    destination = Path(output_path).expanduser().resolve()
    rendered = render_reference_preparation_plan_html(plan)
    try:
        destination.parent.mkdir(parents=True, exist_ok=True)
        with destination.open("x", encoding="utf-8", newline="\n") as handle:
            handle.write(rendered)
    except FileExistsError as error:
        raise ConfigurationError(
            "Reference preparation report already exists and will not be overwritten: "
            f"{destination}"
        ) from error
    except OSError as error:
        raise ConfigurationError(
            f"Could not write reference preparation report {destination}: {error}"
        ) from error
    return destination


def _copied_file(path: str, source: Path, payload_bytes: int, sha256: str) -> dict:
    return {
        "kind": "copied",
        "path": path,
        "source_path": str(source),
        "bytes": payload_bytes,
        "sha256": sha256,
    }


def _generated_file(path: str, payload: bytes) -> dict:
    return {
        "kind": "generated",
        "path": path,
        "bytes": len(payload),
        "sha256": _sha256_bytes(payload),
        "content_utf8": payload.decode("utf-8"),
    }


def _effective_yaml_bytes(effective: Mapping[str, Any]) -> bytes:
    stream = StringIO(newline="\n")
    yaml.safe_dump(
        dict(effective),
        stream,
        sort_keys=False,
        allow_unicode=True,
    )
    return stream.getvalue().encode("utf-8")


def _verify_unchanged(path: Path, expected_sha256: str, label: str) -> None:
    if not path.is_file() or sha256_file(path) != expected_sha256:
        raise ConfigurationError(f"{label} changed while the preparation plan was built: {path}")


def plan_reference_preparation(
    config_path: Path | str,
    *,
    run_id: str,
    allow_existing_destination: bool = False,
) -> dict[str, Any]:
    """Describe exact preparation bytes and paths without creating anything.

    ``allow_existing_destination`` exists only for read-only reconciliation of
    an already approved plan. Normal planning remains fail-closed when the
    prospective immutable destination exists.
    """

    source_config = Path(config_path).expanduser().resolve()
    if not isinstance(run_id, str) or not run_id:
        raise ValueError("run_id must be an explicit nonempty string")
    source_config_bytes = source_config.read_bytes()
    source_config_sha256 = _sha256_bytes(source_config_bytes)
    config = load_config(source_config)
    validate_reference_config(config)
    summary = validate_input_paths(config, source_config)
    template_metadata, subject_metadata = inspect_inputs(summary)
    output_root = resolve_output_directory(config, source_config)
    if output_root.exists() and not output_root.is_dir():
        raise ConfigurationError(f"Configured output root is not a directory: {output_root}")
    resolved_run_id = normalize_run_id(run_id)
    prospective_destination = output_root / resolved_run_id
    destination = (
        prospective_destination.absolute()
        if allow_existing_destination
        else prospective_destination.resolve()
    )
    if destination.exists() and not allow_existing_destination:
        raise ConfigurationError(f"Run directory already exists: {destination}")

    staged_template_relative = Path("input") / "template" / summary.template.name
    staged_subject_relatives = [
        Path("input") / "subjects" / subject.name for subject in summary.subjects
    ]
    inputs = [
        reference_input_record(
            "template",
            summary.template,
            staged_template_relative,
            template_metadata,
        ),
        *(
            reference_input_record("subject", source, staged, metadata)
            for source, staged, metadata in zip(
                summary.subjects,
                staged_subject_relatives,
                subject_metadata,
                strict=True,
            )
        ),
    ]
    effective = effective_reference_config(
        config,
        summary.input_directory,
        summary.template,
        output_root,
    )
    effective_bytes = _effective_yaml_bytes(effective)
    engine_bytes = render_engine_file_bytes(
        config,
        Path("..") / staged_template_relative,
        [Path("..") / path for path in staged_subject_relatives],
    )
    protected_files = [
        _copied_file(
            "config/source-config.yaml",
            source_config,
            len(source_config_bytes),
            source_config_sha256,
        ),
        _generated_file("config/effective-config.yaml", effective_bytes),
        _copied_file(
            staged_template_relative.as_posix(),
            summary.template,
            template_metadata.bytes,
            template_metadata.sha256,
        ),
        *(
            _copied_file(
                staged.as_posix(),
                source,
                metadata.bytes,
                metadata.sha256,
            )
            for source, staged, metadata in zip(
                summary.subjects,
                staged_subject_relatives,
                subject_metadata,
                strict=True,
            )
        ),
        *(
            _generated_file(f"engine/{name}", payload)
            for name, payload in engine_bytes.items()
        ),
    ]
    plan = {
        "schema_version": SCHEMA_VERSION,
        "status": STATUS,
        "source_config": {
            "path": str(source_config),
            "bytes": len(source_config_bytes),
            "sha256": source_config_sha256,
        },
        "run": {
            "run_id": resolved_run_id,
            "output_root": str(output_root),
            "destination": str(destination),
            "destination_exists": False,
        },
        "backend": {
            "id": BACKEND_ID,
            "contract_version": BACKEND_CONTRACT_VERSION,
            "engine_constants": ENGINE_CONSTANTS,
        },
        "planner": {
            "diffeoforge": __version__,
            "python": platform.python_version(),
            "platform": platform.platform(),
            "native_newline": "CRLF" if os.linesep == "\r\n" else "LF",
        },
        "directories": list(PLANNED_DIRECTORIES),
        "input_count": {"templates": 1, "subjects": len(summary.subjects)},
        "inputs": inputs,
        "effective_config": effective,
        "protected_files": protected_files,
        "protected_file_count": len(protected_files),
        "total_protected_bytes": sum(int(item["bytes"]) for item in protected_files),
        "command_preview": build_command(config, destination).as_manifest(),
        "scientific_boundary": SCIENTIFIC_BOUNDARY,
    }
    _validate_plan(plan)
    _verify_unchanged(source_config, source_config_sha256, "Configuration")
    current_summary = validate_input_paths(config, source_config)
    if (
        current_summary.input_directory != summary.input_directory
        or current_summary.template != summary.template
        or current_summary.subjects != summary.subjects
    ):
        raise ConfigurationError(
            "Reference input inventory changed while the preparation plan was built"
        )
    for item in inputs:
        geometry = item["geometry"]
        _verify_unchanged(Path(item["source_path"]), str(geometry["sha256"]), "Input mesh")
    if resolve_output_directory(config, source_config) != output_root:
        raise ConfigurationError(
            "Configured output root changed while the preparation plan was built"
        )
    if destination.exists() and not allow_existing_destination:
        raise ConfigurationError(
            f"Run directory appeared while the preparation plan was built: {destination}"
        )
    return plan
